Repository scale-advisor/back-end, pull requests merged in 2025-06, with the labels that each got.

#181 refactor: requirement, unitProcess 관련 리팩토링
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/requirement/DeleteRequirementPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/requirement/GetRequirementPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/requirementunitprocess/DeleteRequirementUnitProcessPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/requirementunitprocess/GetRequirementUnitProcessPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/unitprocess/DeleteUnitProcessPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/unitprocess/GetUnitProcessPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/adjustmentfactor/DeleteAdjustmentFactorUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/requirement/DeleteRequirementUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/requirement/GetRequirementUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/requirementcategory/DeleteRequirementCategoryUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/requirementunitprocess/DeleteRequirementUnitProcessUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/requirementunitprocess/GetRequirementUnitProcessUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/unitprocess/DeleteUnitProcessUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/unitprocess/GetUnitProcessUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/adjustmentfactor/DeleteAdjustmentFactorService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/requirement/DeleteRequirementService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/requirement/GetRequirementService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/requirementcategory/DeleteRequirementCategoryService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/requirementunitprocess/DeleteRequirementUnitProcessService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/requirementunitprocess/GetRequirementUnitProcessService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/unitprocess/DeleteUnitProcessService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/unitprocess/ETLUnitProcessService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/unitprocess/GetUnitProcessService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/version/DeleteProjectVersionService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/ProjectUnitProcessController.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/response/unitprocess/GetAllUnitProcessResponse.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/RequirementJooqAdapter.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/RequirementUnitProcessJooqAdapter.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/UnitProcessJooqAdapter.kt
Labels: 🎯리팩토링

#184 ProjectAnalysisAPI 리팩토링 관련 PR
  src/main/kotlin/org/scaleadvisor/backend/api/ProjectAnalysisAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/global/job/AnalysisJob.kt
  src/main/kotlin/org/scaleadvisor/backend/global/job/controller/ProjectAnalysisJobController.kt
  src/main/kotlin/org/scaleadvisor/backend/global/job/service/ProjectAnalysisJobService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/unitprocess/UpdateUnitProcessService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/ProjectAnalysisController.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/response/JobIdResponse.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/response/projectanalysis/AnalysisJobStatusResponse.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/response/projectanalysis/JobIdResponse.kt
Labels: ✨기능, 🎯리팩토링, 🛠️버그

#186 Project Analysis 리팩토링 관련 PR
  src/main/kotlin/org/scaleadvisor/backend/global/config/RestTemplateConfig.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/GetJobUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/project/AnalyzeProjectUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/project/AnalyzeProjectService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/project/ProjectAnalysisJobService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/ProjectAnalysisController.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/response/projectanalysis/AnalysisJobStatusResponse.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/job/AnalysisJob.kt
Labels: 🎯리팩토링

#187 fix: Project Requirement API swagger 수정
  src/main/kotlin/org/scaleadvisor/backend/api/ProjectRequirementAPI.kt
Labels: 📄문서

#189 (임시) refactor: Id 중복 이슈 대처 개선
  src/main/kotlin/org/scaleadvisor/backend/global/util/IdUtil.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/requirement/CreateRequirementCategoryService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/requirement/CreateRequirementService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/unitprocess/ETLUnitProcessService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/RequirementUnitProcessJooqAdapter.kt
Labels: 🎯리팩토링

#191 feat: 프로젝트 버전 관리 API 추가
  src/main/kotlin/org/scaleadvisor/backend/api/ProjectVersionAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/requirementunitprocess/GetRequirementUnitProcessPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/version/GetProjectVersionPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/requirement/CreateRequirementUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/requirementunitprocess/GetRequirementUnitProcessUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/version/CreateProjectVersionUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/version/GenerateProjectVersionUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/version/GetProjectVersionUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/version/UpdateProjectVersionUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/requirement/CreateRequirementService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/requirementunitprocess/GetRequirementUnitProcessService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/version/CreateProjectVersionService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/version/GenerateProjectVersionService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/version/GetProjectVersionService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/version/UpdateProjectVersionService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/ProjectVersionController.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/request/version/.gitkeep
  src/main/kotlin/org/scaleadvisor/backend/project/controller/request/version/CreateProjectVersionRequest.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/request/version/UpdateProjectVersionRequest.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/response/version/.gitkeep
  src/main/kotlin/org/scaleadvisor/backend/project/controller/response/version/CreateProjectVersionResponse.kt
  src/main/kotlin/org/scaleadvisor/backend/project/domain/ProjectVersion.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/ProjectVersionJooqAdapter.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/RequirementUnitProcessJooqAdapter.kt
Labels: ✨기능, 🎯리팩토링

#196 refactor: SecurityConfig FilterChain 항목 수정
  src/main/kotlin/org/scaleadvisor/backend/global/config/SecurityConfig.kt
Labels: 🎯리팩토링

#197 fix: 기능 유형 분류 연계 시 메모리 과부하 문제 해결
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/ai/FPClassifierAdapter.kt
Labels: 🚨긴급, 🛠️버그
