Repository scale-advisor/back-end, pull requests merged in 2025-05, with the labels that each got.

#53 feat: (GET) `/projects` API 구현
  src/generated/org/jooq/generated/Keys.java
  src/generated/org/jooq/generated/ScaleAdvisor.java
  src/generated/org/jooq/generated/Tables.java
  src/generated/org/jooq/generated/tables/Project.java
  src/generated/org/jooq/generated/tables/User.java
  src/generated/org/jooq/generated/tables/UserProject.java
  src/generated/org/jooq/generated/tables/daos/UserProjectDao.java
  src/generated/org/jooq/generated/tables/pojos/UserProject.java
  src/generated/org/jooq/generated/tables/records/UserProjectRecord.java
  src/main/kotlin/org/scaleadvisor/backend/api/ProjectAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/project/api/ProjectController.kt
  src/main/kotlin/org/scaleadvisor/backend/project/api/response/CreateProjectResponse.kt
  src/main/kotlin/org/scaleadvisor/backend/project/api/response/FindAllProjectResponse.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/GetProjectRepository.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/CreateProjectUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/GetProjectUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/CreateProjectService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/GetProjectService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/domain/Project.kt
  src/main/kotlin/org/scaleadvisor/backend/project/domain/id/ProjectId.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/ProjectJooqAdapter.kt
  src/main/resources/db/migration/V20250519021519__create_user_project_table.sql
Labels: ✨기능

#61 feat: update project API 구현 및 기존 project cr api 리팩토링
  src/main/kotlin/org/scaleadvisor/backend/api/ProjectAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/project/api/ProjectController.kt
  src/main/kotlin/org/scaleadvisor/backend/project/api/request/UpdateProjectRequest.kt
  src/main/kotlin/org/scaleadvisor/backend/project/api/response/UpdateProjectResponse.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/CreateProjectPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/CreateUserProjectPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/CreateUserProjectRepository.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/GetProjectPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/GetUserProjectPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/UpdateProjectPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/CheckIsProjectMemberUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/GetProjectUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/UpdateProjectUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/CheckIsProjectMemberService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/CreateProjectService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/GetProjectService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/UpdateProjectService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/domain/Project.kt
  src/main/kotlin/org/scaleadvisor/backend/project/domain/id/ProjectId.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/ProjectJooqAdapter.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/UserProjectJooqAdapter.kt
Labels: ✨기능, 🎯리팩토링

#85 feat: File 스키마 추가
  src/main/resources/db/migration/V20250523194201__create_file_table.sql
Labels: ✨기능

#99 feat: 프로젝트 제거 시 파일 제거 로직 추가
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/file/DeleteFilePort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/file/RemoveFilePort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/file/DeleteFileUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/file/RemoveFileUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/file/DeleteFileService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/file/RemoveFileService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/fpweights/DeleteFpWeightsService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/project/DeleteProjectService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/FileJooqAdapter.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/storage/FileLocalStorageAdapter.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/storage/FileS3Adapter.kt
Labels: ✨기능

#102 refactor: 프론트 개발용 Swagger 포트 추가
  .env_sample
  src/main/kotlin/org/scaleadvisor/backend/global/config/SwaggerConfig.kt
  src/main/resources/application.yml
Labels: 🌍인프라

#107 User Delete 수정 관련 PR
  src/main/kotlin/org/scaleadvisor/backend/api/ProjectMemberAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/api/UserAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/member/GetAllProjectMemberPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/member/GetAllProjectMemberUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/member/GetAllProjectMemberService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/ProjectMemberController.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/MemberJooqAdapter.kt
  src/main/kotlin/org/scaleadvisor/backend/user/controller/UserController.kt
  src/main/kotlin/org/scaleadvisor/backend/user/dto/DeleteUserRequest.kt
  src/main/kotlin/org/scaleadvisor/backend/user/service/UserService.kt
Labels: 🎯리팩토링

#108 User Hard Delete 관련 PR
  src/main/kotlin/org/scaleadvisor/backend/api/UserAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/global/link/service/InvitationLinkService.kt
  src/main/kotlin/org/scaleadvisor/backend/global/security/CurrentUserIdExtractor.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/member/CheckIsEditorUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/FpWeightsController.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/ProjectController.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/ProjectFileController.kt
  src/main/kotlin/org/scaleadvisor/backend/user/controller/UserController.kt
  src/main/kotlin/org/scaleadvisor/backend/user/repository/UserRepository.kt
  src/main/kotlin/org/scaleadvisor/backend/user/service/UserService.kt
Labels: 🚨긴급

#113 feat: 이메일 초대 승인 Response dto 추가
  src/main/kotlin/org/scaleadvisor/backend/global/email/controller/InvitationMailController.kt
  src/main/kotlin/org/scaleadvisor/backend/global/email/dto/AcceptInvitationResponse.kt
  src/main/kotlin/org/scaleadvisor/backend/global/email/service/EmailService.kt
Labels: ✨기능

#115 Feat: 요구사항 목록 저장 API 구현
  src/generated/org/jooq/generated/tables/Requirement.java
  src/generated/org/jooq/generated/tables/daos/RequirementDao.java
  src/generated/org/jooq/generated/tables/pojos/Requirement.java
  src/generated/org/jooq/generated/tables/records/RequirementRecord.java
  src/main/kotlin/org/scaleadvisor/backend/api/ProjectRequirementAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/requirement/CreateRequirementPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/requirement/CreateRequirementUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/requirement/CreateRequirementService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/ProjectRequirementController.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/request/requirement/CreateRequirementRequest.kt
  src/main/kotlin/org/scaleadvisor/backend/project/domain/Requirement.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/RequirementJooqAdapter.kt
  src/main/resources/db/migration/V20250526001803__alter_requirement_columns.sql
Labels: ✨기능

#121 feat: requirement, unit_process 컬럼 추가
  src/generated/org/jooq/generated/tables/Requirement.java
  src/generated/org/jooq/generated/tables/UnitProcess.java
  src/generated/org/jooq/generated/tables/daos/RequirementDao.java
  src/generated/org/jooq/generated/tables/daos/UnitProcessDao.java
  src/generated/org/jooq/generated/tables/pojos/Requirement.java
  src/generated/org/jooq/generated/tables/pojos/UnitProcess.java
  src/generated/org/jooq/generated/tables/records/RequirementRecord.java
  src/generated/org/jooq/generated/tables/records/UnitProcessRecord.java
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/requirement/CreateRequirementUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/requirement/CreateRequirementService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/ProjectRequirementController.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/request/requirement/CreateRequirementRequest.kt
  src/main/kotlin/org/scaleadvisor/backend/project/domain/Requirement.kt
  src/main/kotlin/org/scaleadvisor/backend/project/domain/UnitProcess.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/RequirementJooqAdapter.kt
  src/main/resources/db/migration/V20250526210320__add_requirement_definition.sql
  src/main/resources/db/migration/V20250526211555__add_unit_process_is_ambiguous.sql
Labels: ✨기능

#124 feat: 프로젝트 설정 기능 유형 가중치가 없을때, 정부 표준값 사용하도록 구성
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/fpweights/FindFpWeightsPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/fpweights/GetFpWeightsUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/fpweights/GetFpWeightsService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/fpweights/UpdateFpWeightsService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/FpWeightsController.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/response/fpweights/FindFpWeightsResponse.kt
  src/main/kotlin/org/scaleadvisor/backend/project/domain/FpWeights.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/FpWeightsJooqAdapter.kt
Labels: ✨기능

#125 infra: swagger 명세 수정
  src/main/kotlin/org/scaleadvisor/backend/api/Cocomo2Api.kt
  src/main/kotlin/org/scaleadvisor/backend/api/FpWeightsAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/api/ProjectAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/api/ProjectFileAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/api/ProjectMemberAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/api/ProjectOptionAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/api/ProjectRequirementAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/api/ProjectVersionAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/api/UserAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/global/auth/controller/AuthController.kt
  src/main/kotlin/org/scaleadvisor/backend/global/auth/controller/TestController.kt
  src/main/kotlin/org/scaleadvisor/backend/global/email/controller/EmailController.kt
  src/main/kotlin/org/scaleadvisor/backend/global/email/controller/InvitationMailController.kt
  src/main/kotlin/org/scaleadvisor/backend/global/link/controller/InvitationLinkController.kt
  src/main/kotlin/org/scaleadvisor/backend/global/oauth/kakao/KakaoController.kt
  src/main/resources/application.yml
Labels: 🌍인프라, 📄문서

#132 Feat: 보정 계수 관리 API 추가
  src/main/kotlin/org/scaleadvisor/backend/api/ProjectAdjustmentFactorAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/adjustmentfactor/DeleteAdjustmentFactorPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/adjustmentfactor/GetAdjustmentFactorPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/adjustmentfactor/UpdateAdjustmentFactorPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/adjustmentfactor/DeleteAdjustmentFactorUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/adjustmentfactor/GetAdjustmentFactorUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/adjustmentfactor/UpdateAdjustmentFactorUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/adjustmentfactor/DeleteAdjustmentFactorService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/adjustmentfactor/GetAdjustmentFactorService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/adjustmentfactor/UpdateAdjustmentFactorService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/adjustmentfactor/dto/UpdateAdjustmentFactorDTO.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/version/DeleteProjectVersionService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/ProjectAdjustmentFactorController.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/request/adjustmentfactor/UpdateAdjustmentFactorRequest.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/response/adjustmentfactor/GetAdjustmentFactorResponse.kt
  src/main/kotlin/org/scaleadvisor/backend/project/domain/enum/AdjustmentFactorType.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/AdjustmentFactorJooqAdapter.kt
Labels: ✨기능

#134 refactor: 기능 유형 가중치 정보 조회 API 추가 및 기존 불필요한 API 임시 주석 처리
  src/main/kotlin/org/scaleadvisor/backend/api/FpWeightsAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/FpWeightsController.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/response/fpweights/GetFpWeightsResponse.kt
  src/main/kotlin/org/scaleadvisor/backend/project/domain/enum/FunctionType.kt
Labels: ✨기능, 🎯리팩토링

#157 fix: AI 연계 response 파싱 구분자 수정
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/unitprocess/ETLUnitProcessService.kt
Labels: 🚨긴급, 🛠️버그

#161 (임시) fix: pk 중복 이슈 임시 대처
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/project/AnalyzeProjectService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/requirement/CreateRequirementCategoryService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/requirement/CreateRequirementService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/unitprocess/ETLUnitProcessService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/AdjustmentFactorJooqAdapter.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/RequirementCategoryJooqAdapter.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/RequirementJooqAdapter.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/UnitProcessJooqAdapter.kt
Labels: 🚨긴급, 🛠️버그

#162 fix: 요구사항 추출 로직 오류 수정
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/repository/requirementcategory/GetRequirementCategoryPort.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/requirement/GetRequirementUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/requirementcategory/GetRequirementCategoryUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/requirement/GetRequirementService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/requirementcategory/GetRequirementCategoryService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/unitprocess/ETLUnitProcessService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/RequirementCategoryJooqAdapter.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/UnitProcessJooqAdapter.kt
Labels: 🚨긴급, 🛠️버그

#163 fix: 경로 오타 수정
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/ai/client/FPClassifierClient.kt
Labels: 🚨긴급, 🛠️버그

#166 fix: 단위 프로세스 검증 시 빈값일 경우 스킵
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/unitprocess/ValidateUnitProcessService.kt
Labels: 🚨긴급, 🛠️버그

#173 refactor: unitProcess 스키마에 project version 관련 컬럼 추가
  src/generated/org/jooq/generated/Keys.java
  src/generated/org/jooq/generated/tables/Project.java
  src/generated/org/jooq/generated/tables/UnitProcess.java
  src/generated/org/jooq/generated/tables/Version.java
  src/generated/org/jooq/generated/tables/daos/UnitProcessDao.java
  src/generated/org/jooq/generated/tables/pojos/UnitProcess.java
  src/generated/org/jooq/generated/tables/records/UnitProcessRecord.java
  src/main/resources/db/migration/V20250531174424__add_unit_process_project_version_columns.sql
Labels: 🎯리팩토링

#174 Refactor: unit process에 project version 정보 추가
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/unitprocess/ETLUnitProcessService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/domain/UnitProcess.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/ai/FPClassifierAdapter.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/RequirementUnitProcessJooqAdapter.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/UnitProcessJooqAdapter.kt
Labels: 🎯리팩토링

#175 (임시) fix: id 중복 임시 대처
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/RequirementUnitProcessJooqAdapter.kt
Labels: 🚨긴급, 🛠️버그

#178 feat: 요구사항, 단위 프로세스 조회 API 추가
  src/main/kotlin/org/scaleadvisor/backend/api/ProjectRequirementAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/api/ProjectUnitProcessAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/port/usecase/requirement/GetRequirementUseCase.kt
  src/main/kotlin/org/scaleadvisor/backend/project/application/service/requirement/GetRequirementService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/ProjectRequirementController.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/ProjectUnitProcessController.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/request/unitprocess/UpdateAllUnitProcessRequest.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/response/requirement/GetAllRequirementResponse.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/response/unitprocess/GetAllUnitProcessResponse.kt
  src/main/kotlin/org/scaleadvisor/backend/project/domain/ProjectVersion.kt
  src/main/kotlin/org/scaleadvisor/backend/project/infrastructure/database/UnitProcessJooqAdapter.kt
Labels: ✨기능

#179 Project Analysis Jobqueue 초기 구현 관련 PR
  src/main/kotlin/org/scaleadvisor/backend/api/ProjectAnalysisAPI.kt
  src/main/kotlin/org/scaleadvisor/backend/global/config/AsyncExecutorConfig.kt
  src/main/kotlin/org/scaleadvisor/backend/global/job/AnalysisJob.kt
  src/main/kotlin/org/scaleadvisor/backend/global/job/controller/ProjectAnalysisJobController.kt
  src/main/kotlin/org/scaleadvisor/backend/global/job/dto/AnalysisJobStatusResponse.kt
  src/main/kotlin/org/scaleadvisor/backend/global/job/service/ProjectAnalysisJobService.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/ProjectAnalysisController.kt
  src/main/kotlin/org/scaleadvisor/backend/project/controller/response/JobIdResponse.kt
  src/main/resources/application.yml
Labels: ✨기능, 🎯리팩토링
